[package]
name = "remdb-skiplist"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-epoch"] }
parking_lot = "0.12.3"
rand = "0.9.0"

[dev-dependencies]
remdb-thread-pool = { path = "../remdb-thread-pool" }
