[package]
name = "remdb-thread-pool"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "bench"
harness = false

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
tracing = "0.1.41"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.9.0"
