[package]
name = "remdb-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
fs2 = "0.4.3"
parking_lot = "0.12.3"

[dev-dependencies]
anyhow = "1.0.97"
scopeguard = "1.2.0"
tempfile = "3.18.0"
