[package]
name = "remdb-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
parking_lot = "0.12.3"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }